### ISSUE TITLE
How do I run this git project?

### ISSUE THREAD

**Issue by testingBOT9** [ytomasch/rbxjs-plus#1]
![Screenshot_20201230-165243_Termux](https://user-images.githubusercontent.com/75772930/103343808-7a89eb00-4abf-11eb-8cfb-919ea439f0bb.jpg)

**Comment by ytomasch** [comment]
Please read the support documentation from the original project. This requires a running nodejs session. You can then reference the necessary javascript file in the ./lib.

Michael
